sudo: required
services:
  - docker
language: python
  - "2.7"
script:
  - docker pull clelange/cc7-cmssw-cvmfs
  - docker run --rm --privileged -v $PWD:/scripts:ro --device /dev/fuse clelange/cc7-cmssw-cvmfs /bin/bash -c /scripts/test/runCMSSWTest.sh


